[phases.setup]
nixPkgs = ['nodejs@20']

[variables]
NODE_VERSION = "20"

[phases.setup.packages]
bun = true

[phases.build]
commands = [
  "bun install",
  "bun run build"
]

[phases.build.cache]
paths = [
  "node_modules",
  ".bun"
]
